In [17]:
from wordcloud import WordCloud, STOPWORDS 
import matplotlib.pyplot as plt 
from sklearn import metrics
from sklearn.metrics import confusion_matrix
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
import numpy as np # linear algebra
import pandas as pd #data processing

import os
import re


In [18]:


fake_test = pd.read_csv('../fake-news/Fake.csv')
real_test = pd.read_csv('../fake-news/True.csv')
fake_label = [0 for i in range(fake_test.shape[0])]
real_label = [1 for i in range(real_test.shape[0])]
fake_test = fake_test.assign(label = fake_label)
real_test = real_test.assign(label = real_label)

x1 = pd.concat([fake_test,real_test])

x1 = x1.sample(frac=1)



train , test =  x1[:30000], x1[30001:]

print(train.shape,test.shape)


(30000, 5) (14897, 5)


In [19]:
train.head()

title  \
3763   Top U.S. diplomat for Middle East to retire, U...   
4885   Tillerson avoids public conflict with Trump ov...   
7464    Donald Trump Just Posted The Weirdest Ad You’...   
14175  Indian navy the odd man out in Asia's 'Quad' a...   
358     WATCH: Trump Brags About Himself And Trump To...   

                                                    text       subject  \
3763   WASHINGTON (Reuters) - The top U.S. diplomat f...  politicsNews   
4885   WASHINGTON (Reuters) - While he has swallowed ...  politicsNews   
7464   Everyone knows that Republican front runner Do...          News   
14175  NEW DELHI (Reuters) - The Trump administration...     worldnews   
358    It took all of a few seconds for Donald Trump ...          News   

                     date  label  
3763        May 16, 2017       1  
4885      March 17, 2017       1  
7464       March 16, 2016      0  
14175  November 22, 2017       1  
358    September 18, 2017      0

In [20]:
print(train.shape, test.shape)


(30000, 5) (14897, 5)


In [21]:
print(train.isnull().sum())
print('************')
print(test.isnull().sum())

title      0
text       0
subject    0
date       0
label      0
dtype: int64
************
title      0
text       0
subject    0
date       0
label      0
dtype: int64


In [22]:
test=test.fillna(' ')
train=train.fillna(' ')
test['total']= test['title']+' ' + test['text']
train['total']=train['title']+' '+train['text']

# Creating Wordcloud Visuals

# Cleaning and preprocessing 

# 1. Regex

In [23]:
#Remove punctuations from the String  
s = "!</> hello please$$ </>^s!!!u%%bs&&%$cri@@@be^^^&&!& </>*to@# the&&\ cha@@@n##%^^&nel!@# %%$"

In [24]:
s = re.sub(r'[^\w\s]','',s)

In [25]:
#if any substring doesn't hold words or space

In [26]:
print(s)

 hello please subscribe to the channel 


# 2. Tokenization

# 3. StopWords

In [27]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

stop_words = stopwords.words('english')
print(stop_words)

ModuleNotFoundError: No module named 'nltk'

In [28]:
stop_words.append('helo')

NameError: name 'stop_words' is not defined

In [29]:
sentence = "Covid-19 pandemic has impacted many countries and what it did to economy is very stressful"

In [30]:
words = nltk.word_tokenize(sentence)
words = [w for w in words if w not in stop_words]

NameError: name 'nltk' is not defined

In [31]:
words

NameError: name 'words' is not defined

# 4. Lemmatization

In [32]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

input_str="been had done languages cities mice"

ModuleNotFoundError: No module named 'nltk'

In [33]:
#Tokenize the sentence
input_str=nltk.word_tokenize(input_str)

#Lemmatize each word
for word in input_str:
    print(lemmatizer.lemmatize(word))

NameError: name 'nltk' is not defined

# Let's Apply

In [34]:
#lemmatizer=WordNetLemmatizer()
#for index,row in train.iterrows():
    #filter_sentence = ''
    
    #sentence = row['total']
    #sentence = re.sub(r'[^\w\s]','',sentence) #cleaning
    
    #words = nltk.word_tokenize(sentence) #tokenization
    
    #words = [w for w in words if not w in stop_words]  #stopwords removal
    
    #for word in words:
        #filter_sentence = filter_sentence + ' ' + str(lemmatizer.lemmatize(word)).lower()
        
    #train.loc[index,'total'] = filter_sentence
    


# Applying NLP Techniques

In [35]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
X_train = train['total']
Y_train = train['label']
Y_test = test['label']

# Bag-of-words / CountVectorizer

In [37]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [38]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


# TF-iDF Vectorizer

In [39]:
def vectorize_text(features, max_features):
    vectorizer = TfidfVectorizer( stop_words='english',
                            decode_error='strict',
                            analyzer='word',
                            ngram_range=(1, 2),
                            max_features=max_features
                            #max_df=0.5 # Verwendet im ML-Kurs unter Preprocessing                   
                            )
    feature_vec = vectorizer.fit_transform(features)
    return feature_vec.toarray()

In [40]:
tfidf_features = vectorize_text(['hello how are you doing','hi i am doing fine'],30)

In [41]:
#'hello how  doing','hi  doing fine'

In [42]:
tfidf_features

array([[0.44943642, 0.        , 0.        , 0.6316672 , 0.6316672 ,
        0.        , 0.        ],
       [0.33517574, 0.47107781, 0.47107781, 0.        , 0.        ,
        0.47107781, 0.47107781]])

# Let's Apply

In [ ]:
#Feature extraction using count vectorization and tfidf.
count_vectorizer = CountVectorizer()
count_vectorizer.fit_transform(X_train)
freq_term_matrix = count_vectorizer.transform(X_train)
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(freq_term_matrix)
tf_idf_matrix = tfidf.fit_transform(freq_term_matrix)

In [ ]:
tf_idf_matrix.toarray().shape

# Confusion Matrix

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    See full source and example: 
    http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html
    
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    thresh = cm.max() / 2.
    for i, j in iter.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, cm[i, j],
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Modelling

In [ ]:
test_counts = count_vectorizer.transform(test['total'].values)
test_tfidf = tfidf.transform(test_counts)

        

In [ ]:
print(test_tfidf.shape)

In [ ]:
from sklearn.linear_model import LogisticRegression# Logistic Regression

In [ ]:
logreg = LogisticRegression(C=1e7, max_iter = 1000)
logreg.fit(tf_idf_matrix, Y_train)
pred = logreg.predict(test_tfidf)
print('Accuracy of Logistic classifier on training set: {:.2f}'
     .format(logreg.score(tf_idf_matrix, Y_train)))
print('Accuracy of Logistic classifier on test set: {:.2f}'
     .format(logreg.score(test_tfidf, Y_test)))

from sklearn.naive_bayes import MultinomialNB
cm = confusion_matrix(Y_test, pred)
cm

In [ ]:
pred = logreg.predict(test_tfidf)
print('Accuracy of Logistic classifier on training set: {:.2f}'
     .format(logreg.score(tf_idf_matrix, Y_train)))
print('Accuracy of Logistic classifier on test set: {:.2f}'
     .format(logreg.score(test_tfidf, Y_test)))

from sklearn.naive_bayes import MultinomialNB
cm = confusion_matrix(Y_test, pred)
cm

# MultinomialNB

In [ ]:
from sklearn.naive_bayes import MultinomialNB

NB = MultinomialNB()
NB.fit(tf_idf_matrix, Y_train)
pred = NB.predict(test_tfidf)
print('Accuracy of NB  classifier on training set: {:.2f}'
     .format(NB.score(tf_idf_matrix, Y_train)))
print('Accuracy of NB classifier on test set: {:.2f}'
     .format(NB.score(test_tfidf, Y_test)))
cm = confusion_matrix(Y_test, pred)
cm

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score

tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.75)
vec_train=tfidf_vectorizer.fit_transform(X_train.values.astype('U')) 
vec_test=tfidf_vectorizer.transform(test['total'].values.astype('U'))

pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(vec_train,Y_train)
y_pred=pac.predict(vec_test)
score=accuracy_score(Y_test,y_pred)
print(f'PAC Accuracy: {round(score*100,2)}%')
cm = confusion_matrix(Y_test,y_pred)
cm


In [117]:

fake_test = pd.read_csv('../fake-news/Fake.csv')
real_test = pd.read_csv('../fake-news/True.csv')
fake_label = [0 for i in range(fake_test.shape[0])]
real_label = [1 for i in range(real_test.shape[0])]
fake_test = fake_test.assign(label = fake_label)
real_test = real_test.assign(label = real_label)

x1 = pd.concat([fake_test,real_test])
x1['total'] = x1['title'] + " " + x1['text']

X=tfidf_vectorizer.transform(x1['total'].values.astype('U'))
scores = cross_val_score(pac, X, x1['label'].values, cv=5)
print(f'K Fold Accuracy: {round(scores.mean()*100,2)}%')

K Fold Accuracy: 98.83%


In [118]:
X = count_vectorizer.transform(x1['total'].values)
scores = cross_val_score(logreg, X, x1['label'].values, cv=5)
print(f'K Fold Accuracy: {round(scores.mean()*100,2)}%')

K Fold Accuracy: 99.21%


In [119]:
X = count_vectorizer.transform(x1['total'].values)
scores = cross_val_score(NB, X, x1['label'].values, cv=5)
print(f'K Fold Accuracy: {round(scores.mean()*100,2)}%')

K Fold Accuracy: 92.57%


In [120]:
train.head()
train.count()

title      30000
text       30000
subject    30000
date       30000
label      30000
total      30000
dtype: int64

In [121]:
train = pd.read_csv('../fake-news/train.csv')
train = train.dropna()
test = pd.read_csv('../fake-news/test.csv')
train['total'] = train['title'] + " " + train['text']

X=tfidf_vectorizer.transform(train['total'].values.astype('U'))
scores = cross_val_score(pac, X, train['label'].values, cv=5)
print(f'K Fold Accuracy: {round(scores.mean()*100,2)}%')

X = count_vectorizer.transform(train['total'].values)
scores = cross_val_score(logreg, X, train['label'].values, cv=5)
print(f'K Fold Accuracy: {round(scores.mean()*100,2)}%')

X = count_vectorizer.transform(train['total'].values)
scores = cross_val_score(NB, X, train['label'].values, cv=5)
print(f'K Fold Accuracy: {round(scores.mean()*100,2)}%')


K Fold Accuracy: 96.7%
K Fold Accuracy: 96.61%
K Fold Accuracy: 90.84%


In [122]:
X= count_vectorizer.transform(["They hope to raise money to elect dozens of Democrats ahead of next week’s presidential and congressional elections. Cher announced on Twitter: “THURSDAY. Join me and [Hillary Clinton] to SIP TEA AND ELECT DEMOCRATS” Breitbart reports: Tickets for the event start at just $10 and go all the way up to $5,000 for a premium ticket that includes a “pre-event reception with Hillary & Cher.” “Chip in $10 or more to join our virtual conversation with Hillary Clinton & Cher on Thursday, October 29 at 4:30 PM ET,” the event’s description read. “Don’t miss this un-BELIEVE-able opportunity to hear from these two icons! Anything you donate will help elect over 50 House candidates and other Democrats on Election Day.” The event comes just days before next week’s presidential election in which both women are desperately fighting for a victory for Joe Biden over Donald Trump.As part of her 73rd birthday celebrations on Monday, Clinton pleaded with supporters to make a final push to remove Trump from office, four years after her devastating defeat in the 2016 presidential election."])
X1 = count_vectorizer.transform(["it’s the second-high nmber of daiy confirmed infecons since the beginning of the pandemic, behind the 3,004 reported on Sunday. The new cases account for just over three per cent of the 92,328 tests completed over the past day, according to provincial health data. Canada has now seen a total of 228,301 confirmed cases of COVID-19 to date, of which 191,208 have recovered from the disease. Over 11.5 million tests have been completed. Forty-two new deaths were also reported Thursday, bringing the national death toll to 10,074. Over a third of those deaths were historical and did not occur over the past 24 hours."])
#y_pred=pac.predict(X1)
#print(y_pred)
pred2 = logreg.predict(X1)
print(pred1)


[1]
